# Generated by Django 4.2.2 on 2023-06-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='task',
        ),
    ]
